#import './getImageFields'

{
	family {
		title {
			value
		}
		description {
			value
		}
		imageOne {
			responsiveImage {
				...imageFields
			}
		}
		imageTwo {
			responsiveImage {
				...imageFields
			}
		}
	}
}
